### ISSUE TITLE
Unknown module(s): 'Cashfree_Cfcheckout'

### ISSUE THREAD

**Issue by osumnik** [cashfree/cashfree-magento#14]
After updating to 3.1.0

Getting error Unknown module(s): 'Cashfree_Cfcheckout'
While using command: bin/magento module:enable Cashfree_Cfcheckout

Installation method i used:
1.Removed previous version in app->code folder using filezilla
2.Moved cashfree-magento-master to app->code
  (i)Tried renaming cashfree-magento-master to Cashfree

**Comment by prem-cashfree** [comment]
Get our latest [plugin](https://github.com/cashfree/cashfree-magento/releases/tag/v3.2.0) and try to run following command

- bin/magento module:status
- bin/magento module:enable Cashfree_Cfcheckout
- bin/magento setup:upgrade

**Comment by PrashantPunter** [comment]
Hey, what did you name the folder. I, try using the latest release and as I already have a code folder inside the app folder. I try with code,Cashfree_Cfcheckout, cashfree and cashfree-magento-3.3.2 from .giz. But the module is not registering. onces I copy and run bin/magento module:status. I cannot see the Cashfree module in the list of enable or disable module.
