### ISSUE TITLE
Signature Mismatch in Latest Version Magento 2.3.0

### ISSUE THREAD

**Issue by vrajeshpatel4u** [cashfree/cashfree-magento#3]
Hello, I have installed your Extension downloaded from Marketplace. Up to Magento 2.2.6 It's working fine. But Issue in latest Magento 2.3.0. There is error message 'ERROR: Signature mismatch', and redirected to 'https://test.cashfree.com/billpay/checkout/post/submit' url after selecting Cashfree as a Payment Method.
![https___test cashfree com_billpay_checkout_post_submit 1](https://user-images.githubusercontent.com/40518060/50465383-fcb91380-09bc-11e9-8a75-c4ff6fc4f416.png)

**Comment by 4j4yk** [comment]
@vrajeshkpatel They have not updated their plugin yet ?

@akashcashfree When is the next release?

**Comment by vrajeshpatel4u** [comment]
Not yet release.

**Comment by prem-cashfree** [comment]
@4j4yk  and @vrajeshpatel4u You can use our latest plugin.
