### ISSUE TITLE
Issue while testing  - Resource already exists



### ISSUE THREAD

**Issue by gmalhotra02** [cashfree/cashfree-magento#7]
I tried testing on Magento 2.4.1 with cashfree payment gateway, I reached the payment page and I decided to cancel the order, it took me back to the cart page which was perfect as expected. But know whenever I am trying to click the payment gateway option, it takes me to error page which mentions "Resource already exists". 

Let me know if you need more information.

![Screenshot_20210217-021637.jpg](https://user-images.githubusercontent.com/18144176/108166289-fdbbda80-7119-11eb-8506-224a7aa64d63.jpg)

**Comment by prem-cashfree** [comment]
@gmalhotra02 we have update our extension. Please refer to updated one.
